apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzaHViaHN6b25lIiwicGFzc3dvcmQiOiJkY2tyX3BhdF9LZDQ3ZDhhLUxmMHZIaFZmNmw2TlFBQmpEM3MiLCJlbWFpbCI6IlNodWJoYW1iaGF2c2FyMTE5OTMzQGdtYWlsLmNvbSIsImF1dGgiOiJjMmgxWW1oemVtOXVaVHBrWTJ0eVgzQmhkRjlMWkRRM1pEaGhMVXhtTUhaSWFGWm1ObXcyVGxGQlFtcEVNM009In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2026-08-01T12:23:56Z"
  name: dockerhub-secret
  namespace: default
  resourceVersion: "3346"
  uid: f10d3dbc-0636-4cbe-93ba-2635b493bb89
type: kubernetes.io/dockerconfigjson
